window.lessons = [
{
id:'kapitola-01', n:'01', icon:'⚡', title:'Vodiče a nevodiče', tag:'Atom, náboj a elektrické pole', time:'asi 7 minut',
lead:'Elektřina začíná u náboje. Když se náboje mohou pohybovat, vzniká proud; když jsou uvězněné na místě, můžeme pozorovat třeba statickou elektřinu.',
body:[
'<div class="learning-block"><h3>Atom: malé částice, velké rozdíly</h3><p>Atom má kladně nabité protony a neutrální neutrony v jádře. Kolem jsou záporné elektrony. V běžném neutrálním atomu je počet protonů a elektronů stejný. Elektrony ve vnější vrstvě se některým materiálům uvolňují snadno, jiným téměř vůbec.</p></div>',
'<div class="twocol"><div class="note"><b>Vodič</b><p>Má volné nosiče náboje, které se umějí pohybovat. Dobře vedou například měď a hliník.</p></div><div class="note"><b>Izolant</b><p>Elektrony jsou pevněji vázané, proto se náboj materiálem pohybuje obtížně. Příklady: sklo, guma, suchý vzduch.</p></div></div>',
'<div class="learning-block"><h3>Náboj Q a jeho znaménko</h3><p>Proton má kladný náboj, elektron záporný. Stejná znaménka se odpuzují, opačná přitahují. Jednotkou náboje je coulomb (C). Základní náboj elektronu má velikost přibližně 1,602 × 10<sup>−19</sup> C.</p><div class="formula">Q = I · t &nbsp;&nbsp; [C = A · s]</div><p>Jeden coulomb projde vodičem, když jím teče proud 1 A po dobu 1 s.</p></div>',
'<div class="learning-block"><h3>Elektrické pole a napětí</h3><p>Náboj kolem sebe vytváří elektrické pole. To působí silou na další náboje. Siločáry si představ jako mapu směru síly: vycházejí z kladného náboje a končí na záporném; nikdy se nekříží.</p><p>Napětí U říká, kolik energie připadá na jeden coulomb náboje. Zdroj vytvoří mezi svými svorkami napětí a v uzavřeném obvodu tím pohání náboje.</p><div class="formula">U = W / Q &nbsp;&nbsp; [V = J / C]</div></div>',
'<div class="example"><b>Příklad na náboj</b><p>Vodičem teče 2 A po dobu 3 s. Projde náboj Q = 2 · 3 = <strong>6 C</strong>.</p></div>',
'<div class="checklist"><b>Zapamatuj si</b><p>Vodič nabízí pohyblivé náboje · proud je jejich uspořádaný pohyb · napětí dodává energii potřebnou k pohybu.</p></div>'
],
quiz:{q:'Tělesem teče proud 0,5 A po dobu 4 s. Jaký náboj protekl?',opts:['0,125 C','2 C','4,5 C'],ans:1,why:'Použij Q = I · t: 0,5 · 4 = 2 C.'}
},
{
id:'kapitola-02', n:'02', icon:'🔋', title:'Stejnosměrný proud', tag:'Obvody, Ohmův zákon a výkon', time:'asi 12 minut',
lead:'Obvod funguje, když má zdroj, uzavřenou cestu a spotřebič. Zdroj předává energii; náboj obvodem obíhá a spotřebič energii mění například na světlo nebo teplo.',
body:[
'<div class="learning-block"><h3>Proud a jednoduchý obvod</h3><p>Elektrický proud I je náboj, který projde průřezem vodiče za čas. Jednotka je ampér (A). Dohodnutý směr proudu vede od plusu k minusu; elektrony v kovu se pohybují opačně. Obvod tvoří zdroj, vodiče, spotřebič a obvykle spínač.</p><div class="formula">I = Q / t &nbsp;&nbsp; a &nbsp;&nbsp; U = R · I</div><p>Ampérmetr se zapojuje do série, aby měřil stejný proud jako obvod. Voltmetr se zapojuje paralelně ke dvěma bodům, mezi nimiž měří napětí.</p></div>',
'<div class="learning-block"><h3>Odpor vodiče a rezistor</h3><p>Odpor R měří, jak moc vodič brzdí proud; jednotka je ohm (Ω). Závisí na materiálu, délce, průřezu a teplotě. Delší vodič má větší odpor, širší menší. Měď vede lépe než nichrom, a proto mají vodiče z těchto materiálů při podobných rozměrech různé odpory.</p><div class="formula">R = ρ · l / S &nbsp;&nbsp; G = 1/R</div><p>ρ je rezistivita materiálu. Vodivost G (siemens, S) a konduktivita γ (S/m) popisují opačnou stránku: jak snadno proud prochází. U kovů odpor s rostoucí teplotou obvykle roste. Rezistory mohou mít stálou hodnotu, výkonové provedení nebo nastavitelný odpor (potenciometr).</p></div>',
'<div class="example"><b>Ohmův zákon</b><p>Na rezistoru 6 Ω je napětí 12 V. Proud je I = U/R = 12/6 = <strong>2 A</strong>. Pokud znáš dvě z hodnot U, I a R, třetí dopočítáš.</p></div>',
'<div class="twocol"><div class="note"><b>Sériové zapojení</b><p>Součástky jsou za sebou. Proud je všude stejný, napětí se rozdělí. R<sub>celk</sub> = R₁ + R₂ + …</p></div><div class="note"><b>Paralelní zapojení</b><p>Součástky jsou ve větvích mezi stejnými body. Napětí na větvích je stejné, proud se rozdělí. 1/R<sub>celk</sub> = 1/R₁ + 1/R₂ + …</p></div></div><p>Smíšený obvod řeš po částech: nejprve zjednoduš jasné série a paralelní větve.</p>',
'<div class="learning-block"><h3>Kirchhoffovy zákony: počítání v sítích</h3><ul><li><strong>Pro uzel:</strong> proud, který do uzlu přiteče, se rovná proudu, který z něj odteče. Náboj se v uzlu nehromadí.</li><li><strong>Pro smyčku:</strong> součet změn napětí kolem uzavřené cesty je nula. Co zdroj dodá, to se na součástkách spotřebuje.</li></ul><p>Tyto dvě věty fungují i v obvodu, který nejde jednoduše poskládat do série a paralelně.</p></div>',
'<div class="learning-block"><h3>Měřicí rozsah: bočník a předřadník</h3><p>Malý bočníkový rezistor zapojený paralelně s ampérmetrem odvede část proudu a zvětší jeho proudový rozsah. Předřadný rezistor zapojený sériově s voltmetrem omezí proud měřidlem a zvětší jeho napěťový rozsah.</p></div>',
'<div class="learning-block"><h3>Práce, výkon a účinnost</h3><p>Elektrická práce W je předaná energie, měří se v joulech (J); v domácnosti se často používá kilowatthodina. Výkon P říká, kolik energie se předá za sekundu.</p><div class="formula">P = U · I = I²R = U²/R &nbsp;&nbsp; W = P · t</div><p>1 kWh = 3,6 MJ. Účinnost η porovnává užitečný výstupní výkon se vstupním: η = P<sub>výst</sub>/P<sub>vst</sub>. Část energie se mění na ztrátové teplo, proto je η menší než 1.</p></div>',
'<div class="learning-block"><h3>Zdroje, děliče a Théveninův pohled</h3><p>Ideální zdroj napětí drží napětí bez ohledu na odběr; skutečný zdroj má vnitřní odpor r, takže při větším proudu může svorkové napětí klesnout: U = E − I·r. Zdroje se sériově skládají napětím; paralelně je spojuj jen tehdy, když mají shodné napětí a polaritu.</p><p>Nezatížený dělič ze dvou sériových rezistorů dává U₂ = U · R₂/(R₁+R₂). Připojená zátěž výstupní napětí změní. Théveninova poučka dovolí složit složitý lineární obvod z pohledu dvou svorek na jeden náhradní zdroj napětí a jeden sériový odpor.</p></div>',
'<div class="checklist"><b>Rychlá kontrola výsledku</b><p>Je proud v ampérech, odpor v ohmech a napětí ve voltech? V sérii musí být proud stejný. V paralelních větvích musí být stejné napětí.</p></div>'
],
quiz:{q:'Dva rezistory 10 Ω a 20 Ω jsou zapojeny sériově. Jaký je celkový odpor?',opts:['6,7 Ω','20 Ω','30 Ω'],ans:2,why:'V sérii se odpory sčítají: 10 + 20 = 30 Ω.'}
},
{
id:'kapitola-03', n:'03', icon:'🫧', title:'Elektrostatika', tag:'Pole, síla a kondenzátor', time:'asi 8 minut',
lead:'Elektrostatika zkoumá náboje, které se nehýbou jako proud. Jejich pole na sebe působí a může uchovávat energii v kondenzátoru.',
body:[
'<div class="learning-block"><h3>Coulombův zákon</h3><p>Dva bodové náboje na sebe působí elektrickou silou. Větší náboje znamenají větší sílu; větší vzdálenost ji rychle zeslabí. Stejné náboje se odpuzují, opačné přitahují.</p><div class="formula">F = k · |Q₁ · Q₂| / r²</div><p>V materiálu závisí síla také na permitivitě prostředí ε. Ve vakuu je k přibližně 9 · 10⁹ N·m²/C².</p></div>',
'<div class="learning-block"><h3>Intenzita pole E</h3><p>Intenzita elektrického pole popisuje, jak velká síla připadá na jednotkový kladný náboj: E = F/Q. Jednotka je N/C, což je totéž jako V/m. V rovnoměrném poli mezi deskami kondenzátoru platí E = U/d.</p><p>Vodič v elektrostatickém klidu přeskupí volné náboje tak, aby uvnitř vodiče pole vyšlo nulové; náboj se usadí na povrchu. Izolant volné náboje přes sebe nepustí, ale jeho molekuly se v poli nepatrně natočí nebo posunou. Tomu říkáme polarizace.</p></div>',
'<div class="learning-block"><h3>Kondenzátor: dvě plochy, které drží náboj</h3><p>Kondenzátor tvoří dvě vodivé elektrody oddělené izolantem. Po připojení napětí se na deskách nahromadí opačné náboje. Kapacita C udává, kolik náboje připadne na jeden volt; měří se ve faradech (F).</p><div class="formula">C = Q / U &nbsp;&nbsp; energie: W = ½ · C · U²</div><p>Větší plocha desek a vhodné dielektrikum kapacitu zvětšují; větší vzdálenost desek ji zmenšuje. Pokud je pole příliš silné, izolant se prorazí a přestane izolovat.</p></div>',
'<div class="twocol"><div class="note"><b>Kondenzátory paralelně</b><p>Kapacity se sčítají: C<sub>celk</sub> = C₁ + C₂ + …</p></div><div class="note"><b>Kondenzátory sériově</b><p>Sčítají se převrácené hodnoty: 1/C<sub>celk</sub> = 1/C₁ + 1/C₂ + …</p></div></div><p>Existují keramické, fóliové, slídové, elektrolytické i proměnné kondenzátory. Elektrolytické mívají velkou kapacitu, ale mají polaritu, kterou je nutné dodržet.</p>',
'<div class="example"><b>Příklad</b><p>Kondenzátor 100 μF připojíme na 12 V. Uložený náboj je Q = C·U = 0,0001·12 = <strong>0,0012 C = 1,2 mC</strong>.</p></div>',
'<div class="checklist"><b>Zapamatuj si</b><p>Kondenzátor ukládá náboj a energii do elektrického pole. Po odpojení může zůstat nabitý — před prací se ověřuje bezpečné vybití.</p></div>'
],
quiz:{q:'Co se stane s celkovou kapacitou dvou kondenzátorů zapojených paralelně?',opts:['Kapacity se sečtou','Vždy klesne pod menší kapacitu','Je stejná jako u sériového zapojení'],ans:0,why:'U paralelního zapojení se sčítají: Ccelk = C₁ + C₂.'}
},
{
id:'kapitola-04', n:'04', icon:'🔬', title:'Proud v kapalinách, plynech, vakuu a polovodičích', tag:'Různí nosiči náboje', time:'asi 9 minut',
lead:'Kovem přenášejí proud hlavně elektrony. V jiných prostředích se mohou pohybovat i ionty nebo elektrony uvolněné z atomů.',
body:[
'<div class="learning-block"><h3>Kapaliny: ionty a elektrolýza</h3><p>Čistá voda vede proud jen velmi slabě. Když se v kapalině rozpustí kyselina, zásada nebo sůl, rozdělí se na kladné a záporné ionty. Elektrické pole je rozběhne opačnými směry. Takovému roztoku říkáme elektrolyt.</p><p>Při elektrolýze se látky vylučují na elektrodách: kladná elektroda se nazývá anoda, záporná katoda. Elektrolýza se využívá k pokovování i získávání látek. Koroze je nežádoucí chemické poškození kovu; vlhkost a soli ji často urychlují. Faradayův zákon říká, že množství vyloučené látky roste s prošlým nábojem: m = k·I·t.</p></div>',
'<div class="learning-block"><h3>Články, akumulátory a palivové články</h3><p>Galvanický článek mění chemickou energii na elektrickou. Baterie bývá sada článků; akumulátor lze po vybití nabíjet, protože chemické děje jsou vratné. Palivový článek vyrábí elektřinu průběžnou reakcí dodávaného paliva s okysličovadlem.</p></div>',
'<div class="learning-block"><h3>Plyny a vakuum</h3><p>Za běžných podmínek je plyn izolant. Když v něm vzniknou volné elektrony a ionty (ionizace), může vést proud. Krátká jiskra, výbojová trubice, elektrický oblouk a blesk jsou různé podoby výboje. Některé potřebují trvalý vnější zdroj ionizace, jiné pokračují samy.</p><p>Ve vakuu téměř nejsou částice, které by proud nesly. Elektrony se do něj mohou uvolnit zahřátím elektrody nebo světlem a pak je urychlí elektrické pole; na tom pracovaly starší elektronky.</p></div>',
'<div class="learning-block"><h3>Polovodiče: malá změna, velký účinek</h3><p>Křemík má čtyři valenční elektrony a v čistém krystalu je sdílí se sousedními atomy. Zahřátí může uvolnit elektron a zanechat po něm „díru“, která se chová jako kladný nosič. Vodivost polovodičů s rostoucí teplotou obvykle roste.</p><p>Do čistého polovodiče lze přidat malé množství příměsi. Donory dodají volné elektrony a vznikne typ N; akceptory vytvářejí převahu děr a vznikne typ P. Spojení P a N tvoří základ diody, která vede proud snáz jedním směrem. Tím začíná svět tranzistorů, čipů a solárních článků.</p></div>',
'<div class="checklist"><b>Jedna pomůcka</b><p>Kovy: hlavně elektrony · elektrolyt: kladné a záporné ionty · polovodič: elektrony i díry · plyn: proud až po ionizaci.</p></div>'
],
quiz:{q:'Kdo přenáší proud v roztoku kuchyňské soli?',opts:['Pouze volné elektrony v kovové mřížce','Kladné a záporné ionty','Pouze neutrony'],ans:1,why:'V elektrolytu se v elektrickém poli pohybují ionty obou znamének.'}
},
{
id:'kapitola-05', n:'05', icon:'🧲', title:'Magnetismus a elektromagnetismus', tag:'Pole, síly a indukce', time:'asi 10 minut',
lead:'Elektrický proud vytváří magnetické pole. A naopak: měnící se magnetické pole umí vytvořit napětí. Právě tím pracují generátory, transformátory i elektromotory.',
body:[
'<div class="learning-block"><h3>Magnetické pole a materiály</h3><p>Magnet má severní a jižní pól. Opačné póly se přitahují, stejné odpuzují. Magnetické indukční čáry tvoří uzavřené smyčky; mimo magnet vedou od severu k jihu. Diamagnetické látky pole nepatrně vytlačují, paramagnetické látky jsou slabě přitahovány a feromagnetické (například železo) výrazně.</p><p>Proud ve vodiči vytváří kruhové magnetické pole. Směr určí pravidlo pravé ruky: palec ukáže směr proudu, ohnuté prsty směr pole. U cívky se pole jednotlivých závitů sčítá; cívka se chová jako magnet. Jádro z měkkého železa vytvoří silný, snadno ovladatelný elektromagnet.</p></div>',
'<div class="learning-block"><h3>Veličiny a magnetický obvod</h3><p>Intenzita H se měří v A/m a popisuje magnetizující účinek proudu. Magnetická indukce B se měří v teslech (T) a souvisí se silou pole v prostředí; přibližně B = μH. Magnetický tok Φ říká, kolik pole prochází plochou.</p><div class="formula">Φ = B · S · cos α &nbsp;&nbsp; magnetický tok ve Wb</div><p>U feromagnetik roste B zpočátku s H rychle, pak se materiál blíží nasycení. Při cyklickém magnetování se křivka nevrací stejnou cestou: vzniká hystereze. Magnetický obvod lze přirovnat k elektrickému: magnetomotorické napětí NI žene tok Φ přes magnetický odpor R<sub>m</sub>; platí Φ = NI/R<sub>m</sub>.</p></div>',
'<div class="learning-block"><h3>Magnetické síly</h3><p>Na vodič s proudem v magnetickém poli působí síla. Největší je, když vodič míří kolmo k poli; rovnoběžný vodič sílu téměř necítí.</p><div class="formula">F = B · I · l · sin α</div><p>Dva souběžné vodiče s proudem stejným směrem se přitahují; s opačným směrem se odpuzují. Síla otáčí smyčkou v elektromotoru.</p></div>',
'<div class="learning-block"><h3>Indukce: změna pole vyrobí napětí</h3><p>Když se mění magnetický tok procházející závitem, vznikne indukované napětí. Změnu způsobí třeba pohyb magnetu, pohyb vodiče v poli nebo změna proudu v sousední cívce.</p><div class="formula">uᵢ = −N · ΔΦ / Δt</div><p>Minus vyjadřuje Lenzův zákon: indukovaný proud působí proti změně, která ho vyvolala. Vlastní indukčnost L popisuje, jak cívka brání rychlé změně svého proudu: u = −L·ΔI/Δt. Vzájemná indukčnost M popisuje přenos mezi dvěma cívkami — princip transformátoru.</p></div>',
'<div class="learning-block"><h3>Ztráty v jádře</h3><p>Opakované přemagnetování spotřebuje energii na hysterezi. Měnící se tok také indukuje vířivé proudy v kovovém jádře, které jej zahřívají. Ztráty se snižují použitím vhodného materiálu a složením jádra z tenkých navzájem izolovaných plechů.</p></div>',
'<div class="example"><b>Příklad síly na vodič</b><p>Kolmo k poli B = 0,5 T vede vodič délky 0,3 m proud 2 A. F = 0,5·0,3·2 = <strong>0,3 N</strong>.</p></div>'
],
quiz:{q:'Kdy se ve vodiči indukuje napětí?',opts:['Když se magnetický tok vodičem nemění','Když se magnetický tok procházející obvodem mění','Jen když je vodič z mědi'],ans:1,why:'Indukované napětí vzniká při změně magnetického toku obvodem.'}
},
{
id:'kapitola-06', n:'06', icon:'〰️', title:'Střídavý proud', tag:'Sinusovka, fáze a obvody RLC', time:'asi 12 minut',
lead:'U střídavého proudu se velikost i směr pravidelně mění. Síťové napětí je praktický příklad; jeho hladký sinusový průběh se dobře vyrábí i přenáší.',
body:[
'<div class="learning-block"><h3>Sinusový průběh, perioda a frekvence</h3><p>Jedna úplná vlna je perioda T v sekundách. Frekvence f říká, kolikrát se vlna zopakuje za sekundu: f = 1/T. Úhlová frekvence ω = 2πf. U = U<sub>m</sub> sin(ωt + φ) popisuje okamžité napětí; U<sub>m</sub> je maximum a φ počáteční fáze.</p></div>',
'<div class="sine-card"><svg viewBox="0 0 600 100" role="img" aria-label="Animovaný sinusový průběh střídavého napětí"><path class="sine-axis" d="M0 50 H600"/><path class="sine-path" d="M0 50 C25 50 25 10 50 10 S75 90 100 90 125 10 150 10 175 90 200 90 225 10 250 10 275 90 300 90 325 10 350 10 375 90 400 90 425 10 450 10 475 90 500 90 525 10 550 10 575 90 600 90"/></svg><div class="sine-caption">Napětí v čase: plus, nula, minus, nula… a znovu. Efektivní hodnota říká, jaký stejnosměrný účinek by mělo stejné tepelné působení.</div></div>',
'<div class="learning-block"><h3>Efektivní a střední hodnota</h3><p>Pro sinusový průběh je efektivní hodnota to, co běžný voltmetr ukáže jako praktickou velikost střídavého napětí. U<sub>ef</sub> = U<sub>m</sub>/√2 a I<sub>ef</sub> = I<sub>m</sub>/√2. Střední hodnota celé symetrické sinusovky přes periodu je nula; za půlperiodu má velikost 2U<sub>m</sub>/π.</p><p>Generátor vyrábí sinusové napětí otáčením cívky nebo magnetu v magnetickém poli — tok se mění, a proto se indukuje napětí.</p></div>',
'<div class="learning-block"><h3>Rezistor, cívka a kondenzátor ve střídavém obvodu</h3><ul><li><strong>Rezistor R:</strong> proud a napětí jsou ve fázi; energie se mění hlavně na teplo.</li><li><strong>Cívka L:</strong> brání změně proudu. Induktance X<sub>L</sub> = 2πfL roste s frekvencí; proud se za napětím zpožďuje.</li><li><strong>Kondenzátor C:</strong> nabíjí se a vybíjí. Kapacitance X<sub>C</sub> = 1/(2πfC) s frekvencí klesá; proud napětí předbíhá.</li></ul><p>Ve fázorovém diagramu jsou tyto posuny jednoduché: u rezistoru 0°, u cívky 90° dozadu, u kondenzátoru 90° dopředu.</p></div>',
'<div class="learning-block"><h3>Složené obvody R, L, C</h3><p>V sériovém obvodu se proud větvemi rovná a napětí se skládají jako fázory. V paralelním obvodu je stejné napětí a fázory proudů se skládají. Pro sériové RLC platí Z = √(R² + (X<sub>L</sub>−X<sub>C</sub>)²) a I = U/Z. Z je impedance, celková překážka střídavému proudu.</p></div>',
'<div class="learning-block"><h3>Výkon a účiník</h3><p>Zdánlivý výkon S = U·I má jednotku voltampér (VA). Činný výkon P = U·I·cosφ se mění na užitečnou práci a teplo. Jalový výkon Q = U·I·sinφ se periodicky ukládá a vrací v cívkách a kondenzátorech. Účiník cosφ říká, jak účinně se proud využívá.</p></div>',
'<div class="example"><b>Krátký výpočet</b><p>Rezistor 115 Ω připojený na 230 V odebírá I = 230/115 = <strong>2 A</strong>. Pokud je součástka čistě odporová, P = U·I = <strong>460 W</strong>.</p></div>'
],
quiz:{q:'V ideální cívce se při zvyšování frekvence zvětší její indukční reaktance. Platí to?',opts:['Ano, XL = 2πfL','Ne, XL = 1/(2πfL)','Ne, cívka má vždy nulovou reaktanci'],ans:0,why:'Indukční reaktance je XL = 2πfL, takže s frekvencí roste.'}
},
{
id:'kapitola-07', n:'07', icon:'🔺', title:'Trojfázová soustava', tag:'Tři fáze a točivé pole', time:'asi 6 minut',
lead:'Trojfázová síť je tvořena třemi podobnými sinusovými napětími, která jsou posunutá o třetinu periody. Díky tomu přenáší energii plynule a jednoduše roztáčí elektromotory.',
body:[
'<div class="learning-block"><h3>Tři fáze posunuté o 120°</h3><p>Fáze U, V a W mají stejnou frekvenci a podobnou velikost, ale každá začíná o 120° později než předchozí. Součet jejich okamžitých hodnot v souměrné soustavě vychází nula. Generátor má tři cívky, jejichž napětí vznikají při otáčení v magnetickém poli.</p></div>',
'<div class="twocol"><div class="note"><b>Hvězda (Y)</b><p>Jeden konec každé fáze je spojen ve společném uzlu. Vodič mezi fází a uzlem vede fázové napětí; mezi dvěma fázemi je sdružené napětí √3krát větší. Proud vedením se rovná fázovému proudu.</p></div><div class="note"><b>Trojúhelník (Δ)</b><p>Fáze tvoří uzavřený trojúhelník. Napětí jedné fáze je stejné jako sdružené napětí sítě; proud ve vedení je √3krát větší než proud jednou fází.</p></div></div>',
'<div class="learning-block"><h3>Výkon a točivé magnetické pole</h3><p>U souměrného zatížení se činný výkon všech tří fází sečte:</p><div class="formula">P = √3 · U<sub>sd</sub> · I<sub>sd</sub> · cos φ</div><p>Tři proudy v cívkách vytvářejí magnetické pole, které se otáčí. Rotor motoru se za ním snaží otáčet. Proto se trojfázový proud tak dobře hodí pro průmyslové motory.</p></div>',
'<div class="example"><b>Pomůcka pro zapamatování</b><p>Hvězda: napětí ve fázi je menší, proud vedením stejný. Trojúhelník: napětí fáze stejné jako vedení, proud vedením větší.</p></div>',
'<div class="checklist"><b>Pozor při výpočtu</b><p>Ve vzorci pro trojfázový výkon používej sdružené napětí a proud vedením, pokud zadání neříká jinak.</p></div>'
],
quiz:{q:'O kolik stupňů jsou v souměrné trojfázové soustavě posunuté fáze?',opts:['90°','120°','180°'],ans:1,why:'Tři stejně rozložené fáze dělí kruh 360° na třetiny: 120°.'}
},
{
id:'kapitola-08', n:'08', icon:'📡', title:'Elektromagnetické vlnění', tag:'Kmitání, rezonance a přenos zpráv', time:'asi 8 minut',
lead:'Střídající se elektrické a magnetické pole se mohou šířit prostorem jako elektromagnetická vlna. Světlo, rádio i Wi‑Fi patří do stejné rodiny vln.',
body:[
'<div class="learning-block"><h3>LC oscilátor: energie se přelévá</h3><p>Kondenzátor nejprve ukládá energii do elektrického pole. Při vybíjení teče proud cívkou, která ukládá energii do magnetického pole. Potom cívka udržuje proud dál a znovu nabije kondenzátor s opačnou polaritou. V ideálním LC obvodu se energie pravidelně přelévá mezi C a L.</p><p>Odpor R energii postupně mění na teplo, takže vlastní kmitání slábne. Nucené kmitání vznikne, když obvod pravidelně pohání vnější zdroj.</p><div class="formula">f₀ = 1 / (2π√(L · C))</div></div>',
'<div class="learning-block"><h3>Rezonance: správná frekvence zesílí odezvu</h3><p>V RLC obvodu nastane rezonance, když indukční a kapacitní reaktance mají stejnou velikost: X<sub>L</sub> = X<sub>C</sub>. Rezonanční frekvence závisí na L a C. V sériovém obvodu se účinky cívky a kondenzátoru navzájem vyruší, impedance je nejmenší a proud může být největší. V paralelním obvodu je naopak impedance při rezonanci vysoká.</p><p>Rezonanční obvod pomáhá vybrat konkrétní kmitočet, například stanici rádia.</p></div>',
'<div class="learning-block"><h3>Vlnová délka a rychlost šíření</h3><p>Elektromagnetická vlna se skládá z měnícího se elektrického a magnetického pole. Ve vakuu se šíří rychlostí přibližně c = 300 000 km/s. Za jednu periodu urazí jednu vlnovou délku λ.</p><div class="formula">λ = c / f</div><p>Vyšší frekvence znamená kratší vlnovou délku. Rádiové vlny mají delší vlnovou délku než viditelné světlo.</p></div>',
'<div class="learning-block"><h3>Jak vlna přenese informaci</h3><p>Mikrofon nebo kamera převedou zvuk či obraz na elektrický signál. Vysílač informaci zakóduje do nosné vysokofrekvenční vlny (modulace) a pošle ji anténou. Přijímací anténa vlnu zachytí; přijímač vybere požadovanou stanici a oddělí původní informaci (demodulace).</p></div>',
'<div class="checklist"><b>Řetězec přenosu</b><p>Informace → elektrický signál → modulace na nosnou vlnu → anténa → šíření → přijímač → demodulace → původní informace.</p></div>'
],
quiz:{q:'Co se stane s vlnovou délkou, když se frekvence při stejné rychlosti šíření zdvojnásobí?',opts:['Zdvojnásobí se','Zůstane stejná','Zmenší se na polovinu'],ans:2,why:'Platí λ = c/f. Dvojnásobná frekvence znamená poloviční vlnovou délku.'}
}
];